[case]
TYPE = "mesh"
TITLE = "EXAMPLE_2_el_wing"

[flow]
DENSITY = 1.225
VELOCITY = 13.5
VISCOSITY = 1.81e-5
REYNOLDS_LENGTH = 1.4
Y_PLUS = 1.0

[foils]
ELEMENT = ['El_1', 'El_2']
AIRFOIL_FILE = ["AH_79-100_B_Inverted_Selig.dat", "AH_79-100_B_Inverted_Selig.dat"]
CHORD = [0.4, 0.2]            
POSITION = [[0.0, 0.0],[-0.047, 0.009]]   # El_1 is absolute (world coords); each element after is an offset from the previous element's trailing edge
AOA = [0.0, -30.0]              
TE_THICKNESS = [0.0004, 0.0002]  

[farfield]
XMIN = -10.0
XMAX = 20.0
YMIN = -10.0
YMAX = 10.0

[mesh_settings]
DEFAULTS = "multi_element_mesh_parameters.toml"
VISUALISATION = true
SAVE_MESH = true

[global_refinement]
MESH_MAX = 5.0
CELLS_PER_CHORD = 40
GROWTH_RATE = 1.3

[te_refinement]
ENABLED = false
