title = "3_el_wing__foils_AOA_0_neg2p0__003"

[flow]
DENSITY = 1.225
VELOCITY = 13.5
VISCOSITY = 1.81e-5
REYNOLDS_LENGTH = 0.01
Y_PLUS = 1.0

[foils]
ELEMENT = [ "El_1", "El_2", "EL_3",]
AIRFOIL_FILE = [ "AH_79-100_B_Inverted_Selig.dat", "AH_79-100_B_Inverted_Selig.dat", "AH_79-100_B_Inverted_Selig.dat",]
CHORD = [ 0.4, 0.2, 0.15,]
POSITION = [ [ 0.0, 0.0,], [ -0.045, 0.015,], [ -0.04, 0.0017,],]
AOA = [ -2.0, -25.0, -45.0,]
TE_THICKNESS = [ 0.0004, 0.0002, 0.00015,]

[farfield]
XMIN = -5.0
XMAX = 10.0
YMIN = -5.0
YMAX = 5.0

[visualisation]
ENABLED = false

[global_refinement]
MESH_MAX = 5.0
CELLS_PER_CHORD = 75
GROWTH_RATE = 1.2
TE_CELLS = 5
MAX_CURVATURE_ANGLE = 3.0
TE_FAN_ELEMENTS = 8

[boundary_layer]
ENABLED = true
GROWTH_RATE = 1.15
THICKNESS = 0.02

[wake_refinement]
ENABLED = true
MESH_SIZE = 0.01
X_START_CHORDS = -0.1
Y_HALF_HEIGHT_CHORDS = 0.1

[te_refinement]
ENABLED = true
MESH_SIZE = 0.0001
DIST_MAX = 0.01
